name: "SAGE stack bootstrap"
description: "Launch the SAGE microservice stack with docker-compose.marketplace.yml"
author: BOB-DSPM
branding:
  icon: "cloud"
  color: "blue"

inputs:
  compose-file:
    description: "Compose file path"
    required: false
    default: "docker-compose.marketplace.yml"
  host-base:
    description: "Base host URL (scheme + host) for service endpoints"
    required: false
    default: "http://localhost"
  front-port:
    description: "Host port for SAGE front"
    required: false
    default: "8200"
  analyzer-port:
    description: "Host port for analyzer"
    required: false
    default: "9000"
  collector-port:
    description: "Host port for collector"
    required: false
    default: "8000"
  com-show-port:
    description: "Host port for compliance show"
    required: false
    default: "8003"
  com-audit-port:
    description: "Host port for compliance audit"
    required: false
    default: "8103"
  lineage-port:
    description: "Host port for lineage"
    required: false
    default: "8300"
  oss-port:
    description: "Host port for OSS runner"
    required: false
    default: "8800"
  ai-port:
    description: "Host port for identity AI"
    required: false
    default: "8900"
  oss-workdir:
    description: "Workdir path for OSS runner UI"
    required: false
    default: "/tmp"
  pii-model-url:
    description: "Optional PII model endpoint for analyzer"
    required: false
    default: ""
  aws-region:
    description: "AWS region for services that require it"
    required: false
    default: "ap-northeast-2"
  steampipe-db-host:
    description: "Optional Steampipe DB host override"
    required: false
    default: ""
  steampipe-db-port:
    description: "Optional Steampipe DB port override"
    required: false
    default: ""
  steampipe-db-user:
    description: "Optional Steampipe DB user override"
    required: false
    default: ""
  steampipe-db-name:
    description: "Optional Steampipe DB name override"
    required: false
    default: ""
  front-image:
    description: "Override front image tag"
    required: false
    default: ""
  analyzer-image:
    description: "Override analyzer image tag"
    required: false
    default: ""
  collector-image:
    description: "Override collector image tag"
    required: false
    default: ""
  com-show-image:
    description: "Override compliance show image tag"
    required: false
    default: ""
  com-audit-image:
    description: "Override compliance audit image tag"
    required: false
    default: ""
  lineage-image:
    description: "Override lineage image tag"
    required: false
    default: ""
  oss-image:
    description: "Override OSS runner image tag"
    required: false
    default: ""
  ai-image:
    description: "Override identity AI image tag"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Prepare environment variables
      shell: bash
      run: |
        set -euo pipefail
        BASE="${{ inputs['host-base'] }}"
        FRONT_PORT="${{ inputs['front-port'] }}"
        ANALYZER_PORT="${{ inputs['analyzer-port'] }}"
        COLLECTOR_PORT="${{ inputs['collector-port'] }}"
        COM_SHOW_PORT="${{ inputs['com-show-port'] }}"
        COM_AUDIT_PORT="${{ inputs['com-audit-port'] }}"
        LINEAGE_PORT="${{ inputs['lineage-port'] }}"
        OSS_PORT="${{ inputs['oss-port'] }}"
        AI_PORT="${{ inputs['ai-port'] }}"

        echo "HOST_IP=${BASE}" >> "$GITHUB_ENV"
        echo "PUBLIC_BASE=${BASE}:${FRONT_PORT}" >> "$GITHUB_ENV"
        echo "FRONT_PORT=${FRONT_PORT}" >> "$GITHUB_ENV"

        echo "ANALYZER_PORT=${ANALYZER_PORT}" >> "$GITHUB_ENV"
        echo "ANALYZER_URL=${BASE}:${ANALYZER_PORT}" >> "$GITHUB_ENV"
        echo "SAGE_HOST=${BASE}" >> "$GITHUB_ENV"
        echo "PII_MODEL_URL=${{ inputs['pii-model-url'] }}" >> "$GITHUB_ENV"

        echo "COLLECTOR_PORT=${COLLECTOR_PORT}" >> "$GITHUB_ENV"
        echo "COLLECTOR_URL=${BASE}:${COLLECTOR_PORT}" >> "$GITHUB_ENV"
        echo "AWS_REGION=${{ inputs['aws-region'] }}" >> "$GITHUB_ENV"
        echo "AWS_DEFAULT_REGION=${{ inputs['aws-region'] }}" >> "$GITHUB_ENV"

        echo "COM_SHOW_PORT=${COM_SHOW_PORT}" >> "$GITHUB_ENV"
        echo "COM_SHOW_URL=${BASE}:${COM_SHOW_PORT}" >> "$GITHUB_ENV"

        echo "COM_AUDIT_PORT=${COM_AUDIT_PORT}" >> "$GITHUB_ENV"
        echo "COM_AUDIT_URL=${BASE}:${COM_AUDIT_PORT}" >> "$GITHUB_ENV"

        echo "LINEAGE_PORT=${LINEAGE_PORT}" >> "$GITHUB_ENV"
        echo "LINEAGE_URL=${BASE}:${LINEAGE_PORT}" >> "$GITHUB_ENV"

        echo "OSS_PORT=${OSS_PORT}" >> "$GITHUB_ENV"
        echo "OSS_URL=${BASE}:${OSS_PORT}" >> "$GITHUB_ENV"
        echo "REACT_APP_OSS_BASE=${BASE}:${OSS_PORT}/oss" >> "$GITHUB_ENV"
        echo "REACT_APP_OSS_WORKDIR=${{ inputs['oss-workdir'] }}" >> "$GITHUB_ENV"

        echo "AI_PORT=${AI_PORT}" >> "$GITHUB_ENV"

        echo "REACT_APP_API_HOST=${BASE}" >> "$GITHUB_ENV"
        echo "REACT_APP_AEGIS_API_BASE=${BASE}:${ANALYZER_PORT}" >> "$GITHUB_ENV"
        echo "REACT_APP_COLLECTOR_API_BASE=${BASE}:${COLLECTOR_PORT}" >> "$GITHUB_ENV"
        echo "REACT_APP_INVENTORY_API_BASE=${BASE}:${COLLECTOR_PORT}" >> "$GITHUB_ENV"
        echo "REACT_APP_COMPLIANCE_API_BASE=${BASE}:${COM_SHOW_PORT}" >> "$GITHUB_ENV"
        echo "REACT_APP_AUDIT_API_BASE=${BASE}:${COM_AUDIT_PORT}" >> "$GITHUB_ENV"
        echo "REACT_APP_LINEAGE_API_BASE=${BASE}:${LINEAGE_PORT}" >> "$GITHUB_ENV"

        echo "STEAMPIPE_DB_HOST=${{ inputs['steampipe-db-host'] }}" >> "$GITHUB_ENV"
        echo "STEAMPIPE_DB_PORT=${{ inputs['steampipe-db-port'] }}" >> "$GITHUB_ENV"
        echo "STEAMPIPE_DB_USER=${{ inputs['steampipe-db-user'] }}" >> "$GITHUB_ENV"
        echo "STEAMPIPE_DB_NAME=${{ inputs['steampipe-db-name'] }}" >> "$GITHUB_ENV"

        echo "SAGE_FRONT_IMAGE=${{ inputs['front-image'] }}" >> "$GITHUB_ENV"
        echo "SAGE_ANALYZER_IMAGE=${{ inputs['analyzer-image'] }}" >> "$GITHUB_ENV"
        echo "SAGE_COLLECTOR_IMAGE=${{ inputs['collector-image'] }}" >> "$GITHUB_ENV"
        echo "SAGE_COM_SHOW_IMAGE=${{ inputs['com-show-image'] }}" >> "$GITHUB_ENV"
        echo "SAGE_COM_AUDIT_IMAGE=${{ inputs['com-audit-image'] }}" >> "$GITHUB_ENV"
        echo "SAGE_LINEAGE_IMAGE=${{ inputs['lineage-image'] }}" >> "$GITHUB_ENV"
        echo "SAGE_OSS_IMAGE=${{ inputs['oss-image'] }}" >> "$GITHUB_ENV"
        echo "SAGE_AI_IMAGE=${{ inputs['ai-image'] }}" >> "$GITHUB_ENV"

    - name: Validate compose file
      shell: bash
      run: |
        docker compose -f "${{ inputs['compose-file'] }}" config

    - name: Launch SAGE stack
      shell: bash
      run: |
        docker compose -f "${{ inputs['compose-file'] }}" up -d

    - name: Show service status
      shell: bash
      run: |
        docker compose -f "${{ inputs['compose-file'] }}" ps
